use rand::Rng;
use std::{cmp::Ordering, io};
fn main() {
    let mut rng = rand::rng();
    let random_num = rng.random_range(1..100);
    // println!("The random number generated is : {random_num}");
    let mut number_of_tries = 0;
    println!("Guess the Number generated by Program:");
    loop {
        number_of_tries += 1;
        let mut buffer = String::new();
        io::stdin().read_line(&mut buffer).unwrap();

        let guess: u32 = match buffer.trim().parse() {
            Ok(n) => n,
            Err(e) => {
                println!("Check the Input.Got Error: {e:?}");
                println!("Now Enter the number between 1 and 100.");
                continue;
            }
        };
        match guess.cmp(&random_num) {
            Ordering::Less => println!(" Guess is lower than the generated random number"),
            Ordering::Greater => println!(" Guess is higher than the generated ramdom number"),
            Ordering::Equal => {
                println!("Bingo-You Won in {number_of_tries} tries!");
                break;
            }
        }
    }
}
